### ISSUE TITLE
Add `The Magicians`

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/awesome-fantasy#15]
This was suggested by my friend Brent. Looks good? 
https://www.goodreads.com/book/show/6101718-the-magicians

**Comment by RichardLitt** [comment]
Bought. Closing until read.

**Comment by JonathanWolfe** [comment]
I've read this trilogy. I don't know if I would classify it as `awesome`.  The first book is pretty good; it has a decent main character and the progression and twists are novel. Probably a 4/3.75 out of 5. The real problem comes from latter two books in the series, which are awful.  All of the characters are retconned and rules about the universe are changed per page; Nobody acts or responds like a reasonable human would (admittedly sometimes they're not); but worst of all they're just unnecessary and unneeded.  They get a solid 0.5 and 1.5 for books 2 and 3 respectively (definite don't reads).

**Comment by RichardLitt** [comment]
Thanks so much, @JonathanWolfe. I'd heard similar from another friend of mine. Will read it before I decide on this.
