### ISSUE TITLE
Add Stormlight by Brandon Sanderson

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/awesome-fantasy#8]
Suggested on Twitter [here](https://twitter.com/anthonyshort/status/611693043717005312). Anyone read this?

**Comment by CWSpear** [comment]
I have. I am not a super well versed fantasy reader, but I am a huge fan of Sanderson because I was walking through a bookstore on my way to class in college and spotted *Elantris* handbound for $7 and I was poor and couldn't normally afford hard bound books. 

I feel like his magic systems are more well-thought out than many and he does great world building (and I think he's a generally good story teller).

I personally would put every one of his novels on this list, but I may be biased!

The *Stormlight Archive* books (only 2 out of a planned 10 last I heard) are 2 of the longest books out there, and I read on my Kindle and did not realize they were so long until I realized I was some 15 hours in and ~50% done IIRC. I was so engrossed, I hadn't cared. I got the 2nd one the day it came out and read it in about 10 days despite my busy schedule (sleep was sacrificed).

**Comment by RichardLitt** [comment]
Nice! I'll need to pick these up.

Would you mind adding the books you've read to the list? I can't, I haven't read them. :)

**Comment by CWSpear** [comment]
When I get around to having enough time to do it justice!

The *Mistborn* trilogy (well, he plans on doing a trilogy of trilogies, and the last 2 of the 2nd trilogy are due out in the next year or so) is probably his best known and a great read, too. Again, I would recommend all of his stuff, but I think the original *Mistorn* is probably the best place to start (for one, they're much shorter!).

**Comment by SeanSWatkins** [comment]
Sanderson writes a load of good stuff, Elantris, Warbreaker (which is free on his site and is awesome), The Emporer's Soul (. I agree with @CWSpear Mistborn was fantastic, well the first three anyway, still need to start  the second trilogy (As far as I've read the Wax and Wayne Trilogy isn't part of the Trilogy of Trilogies, but just an awesome side project but I might be wrong)

**Comment by RichardLitt** [comment]
@CWSpear I've added both Stormlight and Mistborn using your comments. @SeanSWatkins, if you want to add Elantrics and Warbreaker and the others? They each need their own comments, but if you think they are awesome, add them. 

Thanks both of you!
